//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FTTSP.rc
//
#define ID_CLOCK_TIMER                  1
#define ID_CLOCK_TIMER2                 2
#define ID_CLOCK_TIMER3                 3
#define IDC_STOP_HANDLER                4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FTTSP_DIALOG                102
#define IDS_ERROR_ABNORMAL_TERMINATION  102
#define IDS_ERROR_NO_SERVER_NAME        103
#define IDS_ERROR_NO_SETUP              104
#define IDS_ERROR_CANNOT_OPEN_SETUP     105
#define IDS_ERROR_SETUP                 106
#define IDS_ERROR_CURRENT_RELEASE       107
#define IDS_ERROR_REGISTRY_READ         108
#define IDS_ERROR_NUMBER_CONFIGURATIONS 109
#define IDS_ERROR_NO_DLL                110
#define IDD_LOADPROGRAM_DIALOG          111
#define IDS_ERROR_CREATE_LOAD_PROGRAM   111
#define IDS_ERROR_SYNCHRO_FLAG          112
#define IDS_ERROR_CREATE_PIPE           113
#define IDS_ERROR_TESTER_INSTANCIATION_MAV 114
#define IDS_ERROR_DESTROY_DIRECTORY     115
#define IDS_ERROR_CREATE_DIRECTORY      116
#define IDS_ERROR_ACCESS_DIRECTORY      117
#define IDS_ERROR_FILE_NOT_FOUND        118
#define IDS_ERROR_FILE_OPEN             119
#define IDS_ERROR_FILE_COPY             120
#define IDS_ERROR_UNZIP                 121
#define IDS_ERROR_TIMEOUT_OPEN_PIPE     122
#define IDS_ERROR_COMMUNICATION         123
#define IDS_ERROR_DLL_OPEN              124
#define IDS_LOADING_DLL                 125
#define IDS_LOADING_PRGM                126
#define IDS_PASS                        127
#define IDR_MAINFRAME                   128
#define IDS_FAIL                        128
#define IDD_FTTSP_MAINWINDOW            129
#define IDS_START_UI                    129
#define IDS_WAIT_PRGM_LOAD              130
#define IDS_WAIT_PRGM_INFO              131
#define IDS_FETCHING_MAPCODES           132
#define IDS_MAPCODE_FETCHED             133
#define IDS_PRGM_LOADED                 134
#define IDI_ICONPASS                    134
#define IDS_HND_INIT                    135
#define IDI_ICONFAIL                    135
#define IDI_ICON_UNSUSED                135
#define IDS_ERROR_UI                    136
#define IDD_PASSWORD                    136
#define IDS_ERROR_UI_RELEASE            137
#define IDS_START_HANDLER               138
#define IDS_ERROR_INVALIDBIN            139
#define IDB_BITMAP_REV                  139
#define IDS_DLL_VERSION                 140
#define IDS_ERROR_VERSION_DLL           141
#define IDS_ERROR_NO_PC_NAME            142
#define IDS_NO_SUBCONTRACTOR            143
#define IDS_ERROR_PATH_SUBCONTRACTOR    144
#define IDI_ICON_MEMO                   145
#define IDS_ERROR_SUB_PARAM             145
#define IDS_ERROR_SUB_PATH              146
#define IDS_ERROR_SUB_PARSING           147
#define IDS_ERROR_APPLI                 148
#define IDD_DEBUG_DIALOG                149
#define IDS_START_PHOENIX               149
#define IDS_ERROR_PHOENIX_ID            150
#define IDS_PHOENIX_NOT_STARTED         151
#define IDS_ERROR_PHOENIX_CONNECT       152
#define IDS_ERROR_PHOENIX_PIPE          153
#define IDS_ERROR_TIMER                 154
#define IDS_ERROR_TESTER_INSTANCIATION_TX 155
#define IDI_ICON2                       156
#define IDS_ERROR_TESTER_INSTANCIATION_PHOENIX 156
#define IDI_ICON1                       157
#define IDS_ERROR_PHOENIX_PRGM          157
#define IDS_PHOENIX_CONNECT             158
#define IDS_PHOENIX_ID                  159
#define IDB_BITMAP1                     159
#define IDS_ERROR_TESTER_INSTANCIATION  160
#define IDS_ERROR_FETCH_MAPCODES        161
#define IDS_INSTALL_PRGM                162
#define IDB_SSQ_LOGO                 162
#define IDS_ERROR_HND_INIT              163
#define IDS_START_TX                    164
#define IDS_WAIT_PRGM_LOAD_TX           165
#define IDB_SSQ_LOGO_L               166
#define IDC_PART_ID                     1001
#define IDC_FLOW                        1002
#define IDC_LOT_NUMBER                  1004
#define IDC_LB_NUMBER                   1005
#define IDC_SUB_LOT                     1005
#define IDC_CABLE_NUMBER                1006
#define IDC_OP_NAME                     1007
#define IDC_PRODUCT                     1008
#define IDC_HANDLER                     1009
#define IDC_HANDLER_DLL                 1010
#define IDC_PRODUCT_REV                 1011
#define IDC_LB_REF                      1012
#define IDC_CABLE_REF                   1013
#define IDC_SUB_LOT_NUMBER              1014
#define IDC_HANDLER_ID                  1015
#define IDC_DEGRADED_MODE               1019
#define IDC_CONTROLLERS                 1020
#define IDC_SOCKETS                     1021
#define IDC_INFO                        1023
#define IDC_MESSAGE                     1025
#define IDC_SKTS                        1026
#define IDC_ENGI_MODE                   1027
#define IDC_LASTTESTDURATION            1032
#define IDC_SESSIONDURATION             1033
#define IDC_PASSWORD                    1033
#define IDC_PROGRAMNAME                 1034
#define IDC_TEMPERATURE                 1037
#define IDC_TESTER                      1038
#define IDC_RADIO_PER_DIE               1039
#define IDC_LOADBOARD                   1040
#define IDC_CABLE                       1041
#define IDC_ABOUT_VERS                  1042
#define IDC_DEBUG                       1048
#define IDC_MODE                        1049
#define IDC_DLL_VERSION                 1052
#define IDC_LIST_DLL                    1053
#define IDC_TSP_INFO                    1054
#define IDC_SUB_LOT_NUM                 1057
#define IDC_CHECK_SITE_1                1058
#define IDC_CHECK_SITE_2                1059
#define IDC_CHECK_SITE_3                1060
#define IDC_CHECK_SITE_4                1061
#define IDC_CHECK_SITE_5                1062
#define IDC_CHECK_SITE_6                1063
#define IDC_CHECK_SITE_7                1064
#define IDC_CHECK_SITE_8                1065
#define IDC_STATIC_SITE_USED            1066
#define IDC_STATIC_SFT_REV              1067
#define IDC_TESTER_TYPE                 1069
#define IDC_CHECK_ENGI_OPT              1070
#define IDC_ENGI_FRAME                  1071
#define IDC_TPRGM_EDIT                  1072
#define IDC_BROWSE_TPGRM                1073
#define IDC_RTM                         1075
#define IDC_CHECK_SITES_ALL             1076

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           150
#endif
#endif
